In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("survey_results_public.csv")
schema_df = pd.read_csv("survey_results_schema.csv")

In [7]:
df.set_index("ResponseId", inplace=True)

In [8]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [12]:
df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=113)

In [29]:
df["ConvertedCompYearly"].count()

23435

In [20]:
df["ConvertedCompYearly"].mean()

86155.28726264134

In [21]:
df["ConvertedCompYearly"].median()

65000.0

In [24]:
df["ConvertedCompYearly"].mode()

0    64444.0
Name: ConvertedCompYearly, dtype: float64

In [25]:
df["ConvertedCompYearly"].mode()[0]

64444.0

In [26]:
df.median()

C:\Users\mr\AppData\Local\Temp\ipykernel_2264\530051474.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()

CompTotal              110000.0
WorkExp                     9.0
JobSatPoints_1             10.0
JobSatPoints_4              0.0
JobSatPoints_5              0.0
JobSatPoints_6             20.0
JobSatPoints_7             15.0
JobSatPoints_8             10.0
JobSatPoints_9              5.0
JobSatPoints_10             0.0
JobSatPoints_11             0.0
ConvertedCompYearly     65000.0
JobSat                      7.0
dtype: float64

In [28]:
df.describe()

,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [30]:
df["RemoteWork"].value_counts()

Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
Name: RemoteWork, dtype: int64

In [42]:
df["RemoteWork"].value_counts(normalize=True) # To Show it Like Percentage

Hybrid (some remote, some in-person)    0.419936
Remote                                  0.380086
In-person                               0.199978
Name: RemoteWork, dtype: float64

In [31]:
df["RemoteWork"].unique()

array(['Remote', nan, 'In-person', 'Hybrid (some remote, some in-person)'],
      dtype=object)

In [32]:
df["RemoteWork"].nunique()

3

In [34]:
df.select_dtypes(include='number')

,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,NaN,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
65437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.select_dtypes(include='object')

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,SurveyLength,SurveyEase
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Groupby :-
#### df.groupby('Column To Group by')['Column to Agg'].__()
##### Steps :
 1) Split
 2) Apply Function
 3) Combine Results

In [43]:
df["Country"].value_counts()

United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Central African Republic                                    1
Equatorial Guinea                                           1
Niger                                                       1
Guinea                                                      1
Solomon Islands                                             1
Name: Country, Length: 185, dtype: int64

In [44]:
df.groupby(["Country"])

In [45]:
country_group = df.groupby(["Country"])

In [48]:
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)

In [49]:
country_group.get_group("India") # Grap The Group for India

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,...,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,NaN,6,3,"Developer, front-end",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,NaN,Amazon Web Services (AWS);Digital Ocean;Fireba...,NaN,NaN,jQuery;Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,React Native,OpenGL;React Native,React Native,Docker;npm;Vite;Yarn,Docker;pnpm;Vite,Docker;Vite,...,NaN,NaN,NaN,NaN,I'm not sure,Replacing jobs without options for new employm...,Lack of executive buy-in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
59,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Coding sessions (live or record...,NaN,4,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;JavaScript;Python;SQL,C++;HTML/CSS;Python,C++;HTML/CSS;Python,SQLite,NaN,NaN,NaN,NaN,NaN,Django;Node.js,Django,Django,Arduino,Arduino,Arduino,NaN,NaN,NaN,npm,NaN,NaN,...,Search for answers,Debugging and getting help,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
76,I am learning to code,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,Online Courses or Certification;Coding Bootcamp,NaN,NaN,4,NaN,Designer,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript,Dart;Kotlin;Swift,NaN,MongoDB,NaN,NaN,Firebase;Heroku;VMware,Digital Ocean,NaN,Node.js;React,NaN,NaN,NaN,NaN,NaN,Flutter;Ionic;React Native,NaN,NaN,npm,NaN,NaN,...,NaN,NaN,NaN,NaN,No,Replacing jobs without options for new employm...,Don’t trust the output or answers;Not everyone...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
90,I am learning to code,25-34 years old,"Employed, full-time",In-person,Apples,Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","School (i.e., University, College, etc);Online...",NaN,NaN,2,NaN,Security professional,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL;Visual ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Managed Hosting;VMware,NaN,NaN,ASP.NET;CodeIgniter;Node.js;WordPress,CodeIgniter;Node.js,CodeIgniter;Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NumPy,NaN,NaN,npm,NaN,NaN,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;R...,Not everyone uses them,Yes,Individual contributor,3.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Never,1-2 times a week,Never,60-120 minutes a day,Less than 15 minutes a day,None of these,Observability tools;Knowledge sharing community,Hybrid (on-prem and cloud),AI-powered search (free),Higher Education,80.0,90.0,90.0,50.0,70.0,50.0,50.0,50.0,80.0,Appropriate in length,Easy,NaN,8.0
97,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,11,7,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,Bash/Shell (all shells);C#;JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.NET (5+) ;.NET MAUI,NaN,NaN,NuGet,NaN,NaN,...,NaN,Writing code;Documenting code;Search for answers,NaN,NaN,Yes,Biased results that do not represent diverse v...,"AI tools lack context of codebase, internal a...",Yes,Individual contributor,7.0,Agree,Neither agree nor disagree,Disagree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Tracking my work;Show...,DevOps function;Developer portal or other cent...,Cloud only (single or multi-cloud),A coworker,Software Development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65340,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Social Media;How-to vi...,API document(s) and/or SDK document(s),4,2,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C#;C++;Go;HTML/CSS;JavaScript;Objective-C;Py...,NaN,NaN,Cassandra;Firebase Realtime Database;MariaDB;M...,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,Django;Flask;Next.js;Node.js;React,NaN,NaN,Arduino;Rasberry Pi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65384,I am learning to code,18-24 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,"School (i.e., University, College, etc)",NaN,NaN,9,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65414,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Social Media;How-to videos;Video-based Online ...,NaN,3,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65416,I code primarily as a hobby,35-44 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Social Media;Video-based ...,NaN,4,NaN,System administrator,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65429,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,4,7,"Developer, back-end","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,NaN,Integrated developer community;Frequent update...,India,INR\tIndian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
filt = df["Country"] == "India"
df.loc[filt]

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,...,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,NaN,6,3,"Developer, front-end",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,NaN,Amazon Web Services (AWS);Digital Ocean;Fireba...,NaN,NaN,jQuery;Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,React Native,OpenGL;React Native,React Native,Docker;npm;Vite;Yarn,Docker;pnpm;Vite,Docker;Vite,...,NaN,NaN,NaN,NaN,I'm not sure,Replacing jobs without options for new employm...,Lack of executive buy-in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
59,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Coding sessions (live or record...,NaN,4,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;JavaScript;Python;SQL,C++;HTML/CSS;Python,C++;HTML/CSS;Python,SQLite,NaN,NaN,NaN,NaN,NaN,Django;Node.js,Django,Django,Arduino,Arduino,Arduino,NaN,NaN,NaN,npm,NaN,NaN,...,Search for answers,Debugging and getting help,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
76,I am learning to code,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,Online Courses or Certification;Coding Bootcamp,NaN,NaN,4,NaN,Designer,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript,Dart;Kotlin;Swift,NaN,MongoDB,NaN,NaN,Firebase;Heroku;VMware,Digital Ocean,NaN,Node.js;React,NaN,NaN,NaN,NaN,NaN,Flutter;Ionic;React Native,NaN,NaN,npm,NaN,NaN,...,NaN,NaN,NaN,NaN,No,Replacing jobs without options for new employm...,Don’t trust the output or answers;Not everyone...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
90,I am learning to code,25-34 years old,"Employed, full-time",In-person,Apples,Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","School (i.e., University, College, etc);Online...",NaN,NaN,2,NaN,Security professional,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL;Visual ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Managed Hosting;VMware,NaN,NaN,ASP.NET;CodeIgniter;Node.js;WordPress,CodeIgniter;Node.js,CodeIgniter;Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NumPy,NaN,NaN,npm,NaN,NaN,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;R...,Not everyone uses them,Yes,Individual contributor,3.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Never,1-2 times a week,Never,60-120 minutes a day,Less than 15 minutes a day,None of these,Observability tools;Knowledge sharing community,Hybrid (on-prem and cloud),AI-powered search (free),Higher Education,80.0,90.0,90.0,50.0,70.0,50.0,50.0,50.0,80.0,Appropriate in length,Easy,NaN,8.0
97,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,11,7,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,Bash/Shell (all shells);C#;JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.NET (5+) ;.NET MAUI,NaN,NaN,NuGet,NaN,NaN,...,NaN,Writing code;Documenting code;Search for answers,NaN,NaN,Yes,Biased results that do not represent diverse v...,"AI tools lack context of codebase, internal a...",Yes,Individual contributor,7.0,Agree,Neither agree nor disagree,Disagree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Tracking my work;Show...,DevOps function;Developer portal or other cent...,Cloud only (single or multi-cloud),A coworker,Software Development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65340,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Social Media;How-to vi...,API document(s) and/or SDK document(s),4,2,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C#;C++;Go;HTML/CSS;JavaScript;Objective-C;Py...,NaN,NaN,Cassandra;Firebase Realtime Database;MariaDB;M...,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,Django;Flask;Next.js;Node.js;React,NaN,NaN,Arduino;Rasberry Pi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65384,I am learning to code,18-24 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,"School (i.e., University, College, etc)",NaN,NaN,9,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65414,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Social Media;How-to videos;Video-based Online ...,NaN,3,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65416,I code primarily as a hobby,35-44 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Social Media;Video-based ...,NaN,4,NaN,System administrator,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65429,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,4,7,"Developer, back-end","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,NaN,Integrated developer community;Frequent update...,India,INR\tIndian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df.loc[filt]["DevType"].value_counts()

Developer, full-stack                            1276
Developer, back-end                               671
Student                                           659
Developer, front-end                              309
Developer, mobile                                 247
Developer, desktop or enterprise applications     104
Other (please specify):                           104
Data engineer                                      82
Data scientist or machine learning specialist      80
Developer, AI                                      59
Research & Development role                        54
Developer, embedded applications or devices        53
DevOps specialist                                  52
Engineering manager                                52
Project manager                                    42
Developer, QA or test                              41
Senior Executive (C-Suite, VP, etc.)               39
Academic researcher                                36
Cloud infrastructure engineer                      30
Data or business analyst                           27
Product manager                                    21
Developer Experience                               17
Developer, game or graphics                        17
Blockchain                                         17
Engineer, site reliability                         14
System administrator                               13
Educator                                           12
Security professional                              11
Designer                                           11
Hardware Engineer                                  10
Scientist                                           9
Developer Advocate                                  7
Database administrator                              4
Marketing or sales professional                     2
Name: DevType, dtype: int64

In [61]:
country_group["DevType"].value_counts()

Country      DevType
Afghanistan  Developer, full-stack                   11
             Student                                  6
             Academic researcher                      4
             Data engineer                            3
             Developer, back-end                      3
                                                     ..
Zimbabwe     Developer, front-end                     1
             Educator                                 1
             Engineer, site reliability               1
             Engineering manager                      1
             Senior Executive (C-Suite, VP, etc.)     1
Name: DevType, Length: 2801, dtype: int64

In [58]:
country_group["DevType"].value_counts().loc["India"]

DevType
Developer, full-stack                            1276
Developer, back-end                               671
Student                                           659
Developer, front-end                              309
Developer, mobile                                 247
Developer, desktop or enterprise applications     104
Other (please specify):                           104
Data engineer                                      82
Data scientist or machine learning specialist      80
Developer, AI                                      59
Research & Development role                        54
Developer, embedded applications or devices        53
DevOps specialist                                  52
Engineering manager                                52
Project manager                                    42
Developer, QA or test                              41
Senior Executive (C-Suite, VP, etc.)               39
Academic researcher                                36
Cloud infrastructure engineer                      30
Data or business analyst                           27
Product manager                                    21
Blockchain                                         17
Developer Experience                               17
Developer, game or graphics                        17
Engineer, site reliability                         14
System administrator                               13
Educator                                           12
Designer                                           11
Security professional                              11
Hardware Engineer                                  10
Scientist                                           9
Developer Advocate                                  7
Database administrator                              4
Marketing or sales professional                     2
Name: DevType, dtype: int64

In [64]:
country_group["DevType"].value_counts(normalize=True).loc["India"]*100

DevType
Developer, full-stack                            30.511717
Developer, back-end                              16.044955
Student                                          15.758011
Developer, front-end                              7.388809
Developer, mobile                                 5.906265
Developer, desktop or enterprise applications     2.486848
Other (please specify):                           2.486848
Data engineer                                     1.960784
Data scientist or machine learning specialist     1.912960
Developer, AI                                     1.410808
Research & Development role                       1.291248
Developer, embedded applications or devices       1.267336
DevOps specialist                                 1.243424
Engineering manager                               1.243424
Project manager                                   1.004304
Developer, QA or test                             0.980392
Senior Executive (C-Suite, VP, etc.)              0.932568
Academic researcher                               0.860832
Cloud infrastructure engineer                     0.717360
Data or business analyst                          0.645624
Product manager                                   0.502152
Blockchain                                        0.406504
Developer Experience                              0.406504
Developer, game or graphics                       0.406504
Engineer, site reliability                        0.334768
System administrator                              0.310856
Educator                                          0.286944
Designer                                          0.263032
Security professional                             0.263032
Hardware Engineer                                 0.239120
Scientist                                         0.215208
Developer Advocate                                0.167384
Database administrator                            0.095648
Marketing or sales professional                   0.047824
Name: DevType, dtype: float64

In [66]:
country_group["ConvertedCompYearly"].median()

Country
Afghanistan                               3438.0
Albania                                  35341.0
Algeria                                   7120.0
Andorra                                 123517.0
Angola                                    1754.0
                                          ...
Venezuela, Bolivarian Republic of...     10800.0
Viet Nam                                 12288.5
Yemen                                     5333.0
Zambia                                    2280.0
Zimbabwe                                 18000.0
Name: ConvertedCompYearly, Length: 185, dtype: float64

In [67]:
country_group["ConvertedCompYearly"].median().loc["Germany"]

73036.0

In [69]:
df.groupby("Country")["ConvertedCompYearly"].agg(["mean", "median"])

                                               mean    median
Country
Afghanistan                             5057.250000    3438.0
Albania                                39207.545455   35341.0
Algeria                                91836.700000    7120.0
Andorra                               123517.000000  123517.0
Angola                                  1366.333333    1754.0
...                                             ...       ...
Venezuela, Bolivarian Republic of...   20137.371429   10800.0
Viet Nam                               18803.281250   12288.5
Yemen                                  16498.400000    5333.0
Zambia                                 17054.400000    2280.0
Zimbabwe                               29681.818182   18000.0

[185 rows x 2 columns]

In [70]:
df.groupby("Country")["ConvertedCompYearly"].agg(["mean", "median"]).loc["Canada"]

mean      102348.69116
median     87231.00000
Name: Canada, dtype: float64

In [72]:
filt = df["Country"] == "India"
df.loc[filt]["LanguageHaveWorkedWith"]

ResponseId
18                          HTML/CSS;JavaScript;TypeScript
59                    C;C++;HTML/CSS;JavaScript;Python;SQL
76                                     HTML/CSS;JavaScript
90       C;C++;HTML/CSS;Java;JavaScript;PHP;SQL;Visual ...
97                   Bash/Shell (all shells);C#;JavaScript
                               ...
65340    C;C#;C++;Go;HTML/CSS;JavaScript;Objective-C;Py...
65384                                                  NaN
65414                                                  NaN
65416                                                  NaN
65429                                                  NaN
Name: LanguageHaveWorkedWith, Length: 4231, dtype: object

In [77]:
df.loc[filt]["LanguageHaveWorkedWith"].str.contains("Python")

ResponseId
18       False
59        True
76       False
90       False
97       False
         ...
65340     True
65384      NaN
65414      NaN
65416      NaN
65429      NaN
Name: LanguageHaveWorkedWith, Length: 4231, dtype: object

In [78]:
df.loc[filt]["LanguageHaveWorkedWith"].str.contains("Python").sum()

2128

In [81]:
df.groupby("Country")["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").sum())

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [88]:
# What Percentage of People from each country know python ?
know_python = df.groupby("Country")["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").sum())

know_python.sum()

29797

In [89]:
(know_python / know_python.sum() )* 100

Country
Afghanistan                             0.087257
Albania                                 0.033560
Algeria                                 0.124174
Andorra                                 0.026848
Angola                                  0.030204
                                          ...
Venezuela, Bolivarian Republic of...    0.083901
Viet Nam                                0.463134
Yemen                                   0.033560
Zambia                                  0.026848
Zimbabwe                                0.057053
Name: LanguageHaveWorkedWith, Length: 185, dtype: float64

In [90]:
# Anthor Solution
countries = df["Country"].value_counts()

In [107]:
python_df = pd.concat([know_python, countries], axis='columns', sort=False) 
python_df

                                      LanguageHaveWorkedWith  Country
Afghanistan                                               26       56
Albania                                                   10       49
Algeria                                                   37       77
Andorra                                                    8       15
Angola                                                     9       20
...                                                      ...      ...
Venezuela, Bolivarian Republic of...                      25       69
Viet Nam                                                 138      296
Yemen                                                     10       18
Zambia                                                     8       15
Zimbabwe                                                  17       26

[185 rows x 2 columns]

In [108]:
python_df.rename(columns = {"LanguageHaveWorkedWith":"NumKnownPython", "Country":"NumRespondents"}, inplace=True)

In [109]:
python_df

                                      NumKnownPython  NumRespondents
Afghanistan                                       26              56
Albania                                           10              49
Algeria                                           37              77
Andorra                                            8              15
Angola                                             9              20
...                                              ...             ...
Venezuela, Bolivarian Republic of...              25              69
Viet Nam                                         138             296
Yemen                                             10              18
Zambia                                             8              15
Zimbabwe                                          17              26

[185 rows x 2 columns]

In [110]:
python_df["Percentage"] = python_df["NumKnownPython"] / python_df["NumRespondents"]

In [111]:
python_df

,NumKnownPython,NumRespondents,Percentage
Afghanistan,26,56,0.464286
Albania,10,49,0.204082
Algeria,37,77,0.480519
Andorra,8,15,0.533333
Angola,9,20,0.450000
...,...,...,...
"Venezuela, Bolivarian Republic of...",25,69,0.362319
Viet Nam,138,296,0.466216
Yemen,10,18,0.555556
Zambia,8,15,0.533333
Zimbabwe,17,26,0.653846

In [114]:
python_df.sort_values(by='Percentage', ascending=False, inplace=True)

In [115]:
python_df

                                    NumKnownPython  NumRespondents  Percentage
Lesotho                                          1               1         1.0
Samoa                                            1               1         1.0
Central African Republic                         1               1         1.0
Saint Kitts and Nevis                            1               1         1.0
Niger                                            1               1         1.0
...                                            ...             ...         ...
Guinea-Bissau                                    0               2         0.0
Nauru                                            0               1         0.0
Guinea                                           0               1         0.0
Djibouti                                         0               1         0.0
Micronesia, Federated States of...               0               1         0.0

[185 rows x 3 columns]

In [117]:
python_df.loc["Japan"]

NumKnownPython    167.000000
NumRespondents    288.000000
Percentage          0.579861
Name: Japan, dtype: float64